name: "Share Tag"

on:
  push:
    tags:
      - '*'

jobs:
  post:
    runs-on: ubuntu-latest
    name: "VK"
    steps:
      - name: "Sharing GitHub repository tag to VK"
        uses: ghastore/vk@main
        with:
          gh_api: "https://api.github.com/repos/${{ github.repository }}"
          gh_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          vk_token: "${{ secrets.APP_VK_TOKEN }}"
          vk_owner: "-202249198"
          vk_cr: "https://z17.dev/"
